//
//  NutritionNeedCalculator.swift
//  UmitDietCompanion
//

import Foundation

struct NutritionNeedCalculator: NeedCalculator {

    func calculateNeed(
        snapshot: DailyHealthSnapshot,
        context: CoachingContext
    ) -> Int {

        let mealAdherence = calculateMealAdherence(snapshot: snapshot)

        let mealQuality = calculateMealQuality(snapshot: snapshot)

        let calorieProgress = calculateCalorieProgress(snapshot: snapshot)

        let nutritionScore =
            Double(mealAdherence) * 0.50 +
            Double(mealQuality) * 0.35 +
            Double(calorieProgress) * 0.15

        return max(0, 100 - Int(nutritionScore))
    }

}

// MARK: - Private

private extension NutritionNeedCalculator {

    func calculateMealAdherence(
        snapshot: DailyHealthSnapshot
    ) -> Int {

        // TODO:
        // Evaluate user's selected eating plan
        // Examples:
        // Standard
        // Intermittent Fasting
        // OMAD

        return 100
    }

    func calculateMealQuality(
        snapshot: DailyHealthSnapshot
    ) -> Int {

        // TODO:
        // Average Meal Quality
        // generated by MealAnalyzer

        return 100
    }

    func calculateCalorieProgress(
        snapshot: DailyHealthSnapshot
    ) -> Int {

        // TODO:
        // Calculate percentage of calorie goal

        return 100
    }

}
